# Generated by Django 3.2.19 on 2023-06-12 09:59

import cloudinary_storage.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=users.models.profile_image_upload_path),
        ),
    ]
