# Generated by Django 3.2.19 on 2023-06-09 12:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230609_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, None], upload_to='home/'),
        ),
    ]
