# Generated by Django 3.2.19 on 2023-06-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
