# Generated by Django 3.2.19 on 2023-06-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_post_image_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
